<!DOCTYPE html><html lang="es"><head><meta charset="utf-8"><title>Arqueo #{{ $arqueo->id }}</title><style>
@page{size:58mm auto;margin:0}*{box-sizing:border-box}html,body{width:58mm;margin:0;padding:0;background:#fff;color:#000}body{font-family:"Courier New",monospace;font-size:9px;line-height:1.22}.ticket{width:58mm;padding:3mm 2.5mm}.center{text-align:center}.title{font-size:14px;font-weight:bold}.sep{border-top:1px dashed #000;margin:5px 0}.row{display:flex;justify-content:space-between;gap:5px;margin:2px 0}.row span:first-child{font-weight:bold}.row span:last-child{text-align:right}.section{font-weight:bold;text-align:center;margin:5px 0 3px}.mov{display:grid;grid-template-columns:26px 1fr 52px;gap:3px;margin:2px 0}.mov .m{text-align:right}.total{font-size:13px;font-weight:bold}.muted{font-size:8px}.footer{text-align:center;font-size:8px;margin-top:7px}</style></head><body><div class="ticket">
<div class="center title">CatuDrive</div><div class="center">RESUMEN DE ARQUEO</div><div class="center">ARQUEO #{{ $arqueo->id }}</div><div class="sep"></div>
<div class="row"><span>Estado:</span><span>{{ $arqueo->estado }}</span></div><div class="row"><span>Cajero:</span><span>{{ trim(($arqueo->user?->nombres ?? '').' '.($arqueo->user?->primer_apellido ?? '')) ?: ($arqueo->user?->usuario ?? '-') }}</span></div><div class="row"><span>Apertura:</span><span>{{ $arqueo->fecha_apertura?->format('d/m/Y H:i') ?? '-' }}</span></div><div class="row"><span>Cierre:</span><span>{{ $arqueo->fecha_cierre?->format('d/m/Y H:i') ?? '-' }}</span></div>
<div class="sep"></div><div class="section">RESUMEN DE CAJA</div><div class="row"><span>Saldo anterior:</span><span>Bs {{ number_format((float)$arqueo->saldo_anterior,2) }}</span></div><div class="row"><span>Ingresos válidos:</span><span>Bs {{ number_format($totalIngresos,2) }}</span></div><div class="row"><span>Egresos válidos:</span><span>Bs {{ number_format($totalEgresos,2) }}</span></div><div class="row total"><span>TOTAL:</span><span>Bs {{ number_format($totalGeneral,2) }}</span></div>
<div class="sep"></div><div class="section">POR MÉTODO (NETO)</div>@foreach($porMetodo as $metodo=>$monto)<div class="row"><span>{{ $metodo }}:</span><span>Bs {{ number_format($monto,2) }}</span></div>@endforeach
<div class="sep"></div><div class="section">INGRESOS</div>@forelse($ingresos as $m)<div class="mov"><span>#{{ $m->id }}</span><span>{{ $m->tipoTransaccion?->codigo ?? 'ING' }} {{ $m->detalle }}</span><span class="m">{{ number_format((float)$m->monto,2) }}</span></div>@empty<div class="center muted">Sin ingresos válidos</div>@endforelse
<div class="sep"></div><div class="section">EGRESOS</div>@forelse($egresos as $m)<div class="mov"><span>#{{ $m->id }}</span><span>{{ $m->tipoTransaccion?->codigo ?? 'EGR' }} {{ $m->detalle }}</span><span class="m">{{ number_format((float)$m->monto,2) }}</span></div>@empty<div class="center muted">Sin egresos válidos</div>@endforelse
<div class="sep"></div><div class="footer">Generado {{ $generadoEn->format('d/m/Y H:i') }}<br>FIN DEL ARQUEO</div></div></body></html>
