<!DOCTYPE html><html lang="es"><head><meta charset="utf-8"><title>Arqueo #{{ $arqueo->id }}</title><style>
@page{size:58mm auto;margin:0}*{box-sizing:border-box}html,body{width:58mm;margin:0;padding:0;background:#fff;color:#000}body{font-family:"Courier New",monospace;font-size:8.5px;line-height:1.22}.ticket{width:58mm;padding:3mm 2.5mm}.center{text-align:center}.title{font-size:14px;font-weight:bold}.sep{border-top:1px dashed #000;margin:5px 0}.row{display:flex;justify-content:space-between;gap:5px;margin:2px 0}.row span:first-child{font-weight:bold}.row span:last-child{text-align:right}.section{font-weight:bold;text-align:center;margin:6px 0 3px;font-size:10px}.total{font-size:13px;font-weight:bold}.muted{font-size:8px}.footer{text-align:center;font-size:8px;margin-top:7px}.item{padding:3px 0;border-bottom:1px dotted #999}.item:last-child{border-bottom:0}.itemTop{display:flex;justify-content:space-between;gap:4px;font-weight:bold}.itemDetail{margin-top:1px;word-break:break-word}.itemMeta{display:flex;justify-content:space-between;gap:4px;margin-top:1px;font-size:7.5px}.itemMeta span:last-child{text-align:right}.subtotal{font-weight:bold;margin-top:3px}.badge{font-weight:bold}
</style></head><body><div class="ticket">
<div class="center title">CatuDrive</div><div class="center">DETALLE DE ARQUEO</div><div class="center">ARQUEO #{{ $arqueo->id }}</div><div class="sep"></div>
<div class="row"><span>Estado:</span><span>{{ $arqueo->estado }}</span></div><div class="row"><span>Cajero:</span><span>{{ trim(($arqueo->user?->nombres ?? '').' '.($arqueo->user?->primer_apellido ?? '')) ?: ($arqueo->user?->usuario ?? '-') }}</span></div><div class="row"><span>Apertura:</span><span>{{ $arqueo->fecha_apertura?->format('d/m/Y H:i') ?? '-' }}</span></div><div class="row"><span>Cierre:</span><span>{{ $arqueo->fecha_cierre?->format('d/m/Y H:i') ?? '-' }}</span></div>
<div class="sep"></div><div class="section">RESUMEN DE CAJA</div><div class="row"><span>Saldo anterior:</span><span>Bs {{ number_format((float)$arqueo->saldo_anterior,2) }}</span></div><div class="row"><span>Ingresos válidos:</span><span>Bs {{ number_format($totalIngresos,2) }}</span></div><div class="row"><span>Egresos válidos:</span><span>Bs {{ number_format($totalEgresos,2) }}</span></div><div class="row total"><span>TOTAL:</span><span>Bs {{ number_format($totalGeneral,2) }}</span></div>
<div class="sep"></div><div class="section">TOTALES POR MÉTODO (NETO)</div>@foreach($porMetodo as $metodo=>$monto)<div class="row"><span>{{ $metodo }}:</span><span>Bs {{ number_format($monto,2) }}</span></div>@endforeach
@php
$ventasPasaje=$ingresos->filter(fn($m)=>strtoupper((string)($m->tipoTransaccion?->codigo ?? ''))==='VPASAJE')->values();
$encomiendas=$ingresos->filter(fn($m)=>strtoupper((string)($m->tipoTransaccion?->codigo ?? ''))==='ENCOMIENDA')->values();
$otrosIngresos=$ingresos->reject(fn($m)=>in_array(strtoupper((string)($m->tipoTransaccion?->codigo ?? '')),['VPASAJE','ENCOMIENDA'],true))->values();
@endphp
<div class="sep"></div><div class="section">VENTAS DE PASAJES ({{ $ventasPasaje->count() }})</div>
@forelse($ventasPasaje as $m)<div class="item"><div class="itemTop"><span>#{{ $m->id }}</span><span>Bs {{ number_format((float)$m->monto,2) }}</span></div><div class="itemDetail">{{ $m->detalle }}</div><div class="itemMeta"><span>{{ $m->fecha_registro?->format('d/m H:i') ?? '-' }}</span><span>{{ $m->tipo_pago }}</span></div></div>@empty<div class="center muted">Sin ventas de pasajes en este arqueo</div>@endforelse
<div class="subtotal row"><span>Total pasajes:</span><span>Bs {{ number_format((float)$ventasPasaje->sum('monto'),2) }}</span></div>
<div class="sep"></div><div class="section">ENCOMIENDAS ({{ $encomiendas->count() }})</div>
@forelse($encomiendas as $m)<div class="item"><div class="itemTop"><span>#{{ $m->id }}</span><span>Bs {{ number_format((float)$m->monto,2) }}</span></div><div class="itemDetail">{{ $m->detalle }}</div><div class="itemMeta"><span>{{ $m->fecha_registro?->format('d/m H:i') ?? '-' }}</span><span>{{ $m->tipo_pago }}</span></div></div>@empty<div class="center muted">Sin encomiendas en este arqueo</div>@endforelse
<div class="subtotal row"><span>Total encomiendas:</span><span>Bs {{ number_format((float)$encomiendas->sum('monto'),2) }}</span></div>
<div class="sep"></div><div class="section">OTROS INGRESOS ({{ $otrosIngresos->count() }})</div>
@forelse($otrosIngresos as $m)<div class="item"><div class="itemTop"><span>#{{ $m->id }} {{ $m->tipoTransaccion?->codigo ?? 'ING' }}</span><span>Bs {{ number_format((float)$m->monto,2) }}</span></div><div class="itemDetail">{{ $m->detalle }}</div><div class="itemMeta"><span>{{ $m->fecha_registro?->format('d/m H:i') ?? '-' }}</span><span>{{ $m->tipo_pago }}</span></div></div>@empty<div class="center muted">Sin otros ingresos</div>@endforelse
<div class="subtotal row"><span>Total otros ingresos:</span><span>Bs {{ number_format((float)$otrosIngresos->sum('monto'),2) }}</span></div>
<div class="sep"></div><div class="section">EGRESOS ({{ $egresos->count() }})</div>
@forelse($egresos as $m)<div class="item"><div class="itemTop"><span>#{{ $m->id }} {{ $m->tipoTransaccion?->codigo ?? 'EGR' }}</span><span>Bs {{ number_format((float)$m->monto,2) }}</span></div><div class="itemDetail">{{ $m->detalle }}</div><div class="itemMeta"><span>{{ $m->fecha_registro?->format('d/m H:i') ?? '-' }}</span><span>{{ $m->tipo_pago }}</span></div></div>@empty<div class="center muted">Sin egresos válidos</div>@endforelse
<div class="subtotal row"><span>Total egresos:</span><span>Bs {{ number_format((float)$egresos->sum('monto'),2) }}</span></div>
<div class="sep"></div><div class="row total"><span>TOTAL FINAL:</span><span>Bs {{ number_format($totalGeneral,2) }}</span></div><div class="sep"></div><div class="footer">Generado {{ $generadoEn->format('d/m/Y H:i') }}<br>FIN DEL ARQUEO</div></div></body></html>
